#!/bin/bash
# ~/.dmenurc
DMENU_FN="TamzenForPowerline:pixelsize=14"
DMENU_NB="#$(xrdb -query | sed -n 's/URxvt\*background:.*\#//p')"
DMENU_NF="#$(xrdb -query | sed -n 's/URxvt\*foreground:.*\#//p')"
DMENU_SB="#$(xrdb -query | sed -n 's/URxvt\*foreground:.*\#//p')"
DMENU_SF="#$(xrdb -query | sed -n 's/URxvt\*background:.*\#//p')"
TERMINAL_CMD="urxvt"
PANEL_HEIGHT="35"
DMENU_OPTIONS="-fn $DMENU_FN -nb $DMENU_NB -nf $DMENU_NF -sf $DMENU_SF -sb $DMENU_SB"
export DMENU_FN DMENU_NB DMENU_NF DMENU_SF DMENU_SB DMENU_OPTIONS PANEL_HEIGHT
