#!/bin/bash
#
# Profile for X11
#

# Set X keymap because reasons
setxkbmap ch

# Merge X resources for urxvt
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi


## Start applications
#ibus-daemon -drx
#exec bspwm &
#launch sxhkd color xrdb polybar compton hp
#nm-applet
#/usr/bin/polkit-kde-authentication-agent-1
#start_jack &
#sleep 1
#launch color bspwm
