config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  longkey: false
dotfiles:
  d_bspwm:
    dst: ~/.config/bspwm
    src: config/bspwm
  d_sxhkd:
    dst: ~/.config/sxhkd
    src: config/sxhkd
  f_alias:
    dst: ~/.alias
    src: alias
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
profiles:
  sun:
    dotfiles:
    - f_alias
    - f_zshrc
    - f_xinitrc
    - d_bspwm
    - d_sxhkd
