actions:
  bspwm: ~/.config/bspwm/bspwmrc
  envd_link: rm ~/.config/environment.d/10-xdg-user-dirs.conf; ln -s ~/.config/user-dirs.dirs
    ~/.config/environment.d/10-xdg-user-dirs.conf
  polybar: ~/.config/polybar/launch.sh &> /dev/null &
  sxhkd: pkill -USR1 -x sxhkd
  xres: xrdb -merge ~/.Xresources
config:
  backup: false
  banner: false
  create: true
  dotpath: dotfiles
  keepdot: true
  longkey: false
dotfiles:
  d_bin:
    dst: ~/bin
    src: bin
  d_bspwm:
    actions:
    - bspwm
    dst: ~/.config/bspwm
    src: .config/bspwm
  d_environment.d:
    actions:
    - envd_link
    dst: ~/.config/environment.d
    src: .config/environment.d
  d_polybar:
    actions:
    - polybar
    dst: ~/.config/polybar
    src: .config/polybar
  d_rofi:
    dst: ~/.config/rofi
    src: .config/rofi
  d_sxhkd:
    actions:
    - sxhkd
    dst: ~/.config/sxhkd
    src: .config/sxhkd
  f_alias:
    dst: ~/.alias
    src: .alias
  f_profile:
    dst: ~/.profile
    src: .profile
  f_xinitrc:
    dst: ~/.xinitrc
    src: .xinitrc
  f_xprofile:
    dst: ~/.xprofile
    src: .xprofile
  f_xresources:
    actions:
    - xres
    dst: ~/.Xresources
    src: .Xresources
  f_zshrc:
    dst: ~/.zshrc
    src: .zshrc
profiles:
  common:
    dotfiles:
    - f_xinitrc
    - f_xprofile
    - f_xresources
    - f_profile
    - f_alias
    - d_bin
    - d_environment.d
    - f_zshrc
    - d_bspwm
    - d_sxhkd
    - d_polybar
    - d_rofi
  sun:
    dotfiles: []
    include:
    - common
  teegardenb:
    dotfiles: []
    include:
    - common
