actions:
  bspwm: ~/.config/bspwm/bspwmrc
  compton: killall compton; compton -b
  envd_link: rm ~/.config/environment.d/10-xdg-user-dirs.conf; ln -s ~/.config/user-dirs.dirs
    ~/.config/environment.d/10-xdg-user-dirs.conf
  systemctl_import_env: systemctl --user import-environment
  polybar: ~/.config/polybar/launch.sh &> /dev/null &
  sxhkd: pkill -USR1 -x sxhkd
  xres: xrdb -merge ~/.Xresources
  spicetify: spicetify update
  discord_sass: sassc ~/.config/discord/user.scss > ~/.config/discord/user.css
config:
  backup: false
  banner: false
  create: true
  dotpath: dotfiles
  keepdot: true
  longkey: false
  cmpignore:
  - '*/README.md'
  - '*/.gitkeep'
  upignore:
  - '*/README.md'
  - '*/.gitkeep'
  instignore:
  - '*/README.md'
  - '*/.gitkeep'
dotfiles:
  d_bin:
    dst: ~/bin
    src: bin
  d_bspwm:
    actions:
    - bspwm
    dst: ~/.config/bspwm
    src: .config/bspwm
  d_environment.d:
    actions:
    - envd_link
    - systemctl_import_env
    dst: ~/.config/environment.d
    src: .config/environment.d
  d_polybar:
    actions:
    - polybar
    dst: ~/.config/polybar
    src: .config/polybar
  d_rofi:
    dst: ~/.config/rofi
    src: .config/rofi
  d_sxhkd:
    actions:
    - sxhkd
    dst: ~/.config/sxhkd
    src: .config/sxhkd
  f_alias:
    dst: ~/.alias
    src: .alias
  f_atheister.zsh-theme:
    dst: ~/.oh-my-zsh/custom/themes/atheister.zsh-theme
    src: .oh-my-zsh/custom/themes/atheister.zsh-theme
  f_compton.conf:
    actions:
    - compton
    dst: ~/.config/compton.conf
    src: .config/compton.conf
  f_fonts.conf:
    dst: ~/.config/fontconfig/fonts.conf
    src: .config/fontconfig/fonts.conf
  f_profile:
    dst: ~/.profile
    src: .profile
  f_xinitrc:
    dst: ~/.xinitrc
    src: .xinitrc
  f_xprofile:
    dst: ~/.xprofile
    src: .xprofile
  f_xresources:
    actions:
    - xres
    dst: ~/.Xresources
    src: .Xresources
  f_xresources.d:
    actions:
    - xres
    dst: ~/.config/Xresources.d
    src: .config/Xresources.d
  d_wal:
    src: .config/wal
    dst: ~/.config/wal
  f_zshrc:
    dst: ~/.zshrc
    src: .zshrc
  f_config.ini:
    actions:
    - spicetify
    src: .config/spicetify/config.ini
    dst: ~/.config/spicetify/config.ini
  d_themes:
    actions:
    - spicetify
    src: .config/spicetify/Themes
    dst: ~/.config/spicetify/Themes
  f_bdiscord:
    src: bin/bdiscord
    dst: ~/bin/bdiscord
  f_user.scss:
    actions:
    - discord_sass
    src: .config/discord/user.scss
    dst: ~/.config/discord/user.scss
profiles:
  common:
    dotfiles:
    - f_xinitrc
    - f_xprofile
    - f_xresources
    - f_xresources.d
    - d_wal
    - f_profile
    - f_alias
    - d_bin
    - d_environment.d
    - f_zshrc
    - f_atheister.zsh-theme
    - d_bspwm
    - f_compton.conf
    - d_sxhkd
    - d_polybar
    - d_rofi
    - f_fonts.conf
    - f_config.ini
    - d_themes
    - f_bdiscord
    - f_user.scss
  sun:
    dotfiles: []
    include:
    - common
  teegardenb:
    dotfiles: []
    include:
    - common
  kepler22b:
    dotfiles: []
    include:
    - common
