config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  longkey: false
dotfiles:
  d_bin:
    dst: ~/bin
    src: bin
  d_bspwm:
    dst: ~/.config/bspwm
    src: config/bspwm
  d_rofi:
    dst: ~/.config/rofi
    src: config/rofi
  d_sxhkd:
    dst: ~/.config/sxhkd
    src: config/sxhkd
  f_alias:
    dst: ~/.alias
    src: alias
  f_profile:
    dst: ~/.profile
    src: profile
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  f_xprofile:
    dst: ~/.xprofile
    src: xprofile
  f_xresources:
    dst: ~/.Xresources
    src: Xresources
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
profiles:
  sun:
    dotfiles:
    - f_alias
    - f_zshrc
    - f_xinitrc
    - d_bspwm
    - d_sxhkd
    - d_rofi
    - f_xresources
    - f_xprofile
    - f_profile
    - d_bin
  teegardenb:
    dotfiles:
    - f_alias
    - f_zshrc
    - f_xinitrc
    - d_bspwm
    - d_sxhkd
    - d_rofi
    - f_xresources
    - f_xprofile
    - f_profile
    - d_bin
