# Shell variables
# Generated by 'wal'
wallpaper='None'

# Special
background='#1c1a1a'
foreground='#beb4b4'
cursor='#beb4b4'

# Colors
color0='#262424'
color1='#c0392b'
color2='#27ae39'
color3='#eca30f'
color4='#295dc1'
color5='#8a37ad'
color6='#169e9e'
color7='#867c7c'
color8='#444040'
color9='#e74c3c'
color10='#2ecc55'
color11='#ffc30c'
color12='#2e7ef2'
color13='#a156d7'
color14='#1bbbc4'
color15='#aca2a2'
