#! /bin/sh

###
### Geometry
###
bspc config window_gap		0
bspc config top_padding		30
bspc config left_padding	0
bspc config right_padding	0
bspc config bottom_padding	0
bspc config border_width	0

###
### Colors
###
if [ -f "${XDG_CACHE_HOME:=~/.cache}/wal/colors.sh" ]; then
    . "${XDG_CACHE_HOME:=~/.cache}/wal/colors.sh"
else
    echo "Couldn't find wal generated theme at ${XDG_CACHE_HOME:=~/.cache}/wal/colors.sh" >&2
fi
bspc config normal_border_color		"${background:=#262424}"
bspc config focused_border_color	"${color4:=#0076FF}"
bspc config active_border_color     "${color12:=#00A0FF}"
bspc config presel_feedback_color	"${color7:=#302e2e}"

###
### Various settings
###
bspc config gapless_monocle     false 
bspc config borderless_monocle  false
bspc config single_monocle      true
#bspc config paddingless_monocle false
#bspc config ignore_ewmh_focus      true
#bspc config initial_polarity second_child
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config honor_size_hints false # urxvt tries to increment only by font character dimensions
bspc config focus_follows_pointer true
#bspc config pointer_follows_focus true #Some keybindings automatically enable and disable this setting
bspc config split_ratio         0.5

###
### Workspace labeling
###
bspc monitor -d 一 二 三 四 五 六 七 八 九 十
#bspc monitor -d • • • • • • • • • •
#bspc monitor -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor -d i ii iii iv v vi vii viii ix x
#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d One Two Three Four Five Six Seven Eight Nine Ten

###
### Rules
###
#bspc rule -a screenkey --unmanage
#bspc rule -a gcolor2 state=floating center=true
#bspc rule -a lxappearance state=floating center=true
#bspc rule -a gmrun state=floating center=true
#bspc rule -a lxterminal state=floating center=true sticky=true
#bspc rule -a urxvt state=floating center=true
#bspc rule -a viewnior state=floating center=true
#bspc rule -a file-roller state=floating center=true
#bspc rule -a floaterm state=floating center=true
#bspc rule -a spotify state=pseudo_tiled
##bspc rule -a nautilus state=pseudo_tiled
##bspc rule -a skype state=pseudo_tiled
#bspc rule -a file-roller state=pseudo_tiled
#bspc rule -a transmission-gtk state=pseudo_tiled
#bspc rule -a conky sticky=on manage=off lower=on
#bspc rule -a astime sticky=on
#bspc rule -a yad state=floating
#bspc rule -a Docky layer=above border=off manage=on
#bspc rule -a Plank layer=above border=off manage=on
#bspc rule -a wbar layer=above
#bspc rule -a dockbarx layer=above
#bspc rule -a google-chrome-unstable private=on
#bspc rule -a google-chrome-stable private=on
#bspc rule -a chromium private=on
#bspc rule -a firefox private=on
#bspc rule -a midori private=on
#bspc rule -a gnome-pie border=off manage=off
#bspc rule -a wpa_gui state=pseudo_tiled
#bspc rule -a 9menu border=off manage=off
#bspc rule -a tint2 border=off manage=off


##  Autogap adjusts windowgap automatically according to the number of
##  windows on the desktop. Using it disables negative window gap.
#autogap &

##  This script balances all windows when new one is spawned 
#euclid_balancer &

## Edge-switcher switches to next workspace when moves moves to the 
## edge of the monitor (behavior similar to enlightenment)
#edge-switcher &

###
### External rules
###

# Pseudo automatic mode: always splits focused window when opening new window
bspc config external_rules_command /usr/bin/pseudo_automatic_mode

# Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command /usr/bin/adjust-new-window
